### ISSUE TITLE
More lightweight base image

### ISSUE THREAD

**Issue by ugurarpaci** [aws/amazon-linux-docker-images#12]
Hello,

I just wonder if you guys have any plan to make this docker base image more lightweight instead of providing more general purpose image? I see that the python and some other shared libraries are installed (which is not required for all kind of applications like written in JAVA or Go) which makes it big and more vulnerable.

**Comment by jhaynes** [comment]
Hi @ugurarpaci, thanks for the question. 

We're certainly open to paring things down in the image, but many of those extra packages are installed due to dependencies of yum/rpm (e.g. python). See `repoquery` from the `yum-utils` package: running `repoquery --tree-requires yum` will show a big pile of dependencies. 

That said, there are a few options available for compiled languages and small containers. One of the best options is to use [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) (since Docker 17.05) and only output your build artifacts into the final container.

**Comment by ugurarpaci** [comment]
Hello,

That is correct. This is a great image for general purpose application deployment and since it has a long-term support, it`s adoption should be getting higher. However, in order to satisfy enterprise app deployment requirements, it would be great to have an image from AWS side like alpine or distroless base images that includes almost nothing but the application itself. The challenge would be making it easier to maintain and use for the developers.

People are looking for such a thing and this is why I wanted to mention about this.

Thanks for the answer.
