### ISSUE TITLE
AWS Linux LTS 2 - Vulnerabilities

### ISSUE THREAD

**Issue by FW-John** [aws/amazon-linux-docker-images#8]
A docker scan of amazonlinux:latest contains the following vulnerabilities.

[amazonlinux-latest_vulnerbiltiies_2018-01-24.pdf](https://github.com/aws/amazon-linux-docker-images/files/1661786/amazonlinux-latest_vulnerbiltiies_2018-01-24.pdf)

**Comment by yosifkit** [comment]
(This is my outside opinion based on experience in maintaining the Docker Official Images, I do not speak for the Amazon Linux maintainers)

When vulnerabilities are found, it is usually the case that fixes are not available for the specified packages.  Sometimes there are stated reasons (like [CVE-2014-6277](https://access.redhat.com/security/cve/cve-2014-6277)), and sometimes it is just "will not fix" (like [CVE-2016-5636](https://access.redhat.com/security/cve/CVE-2016-5636)).

Lets start with the first two vulnerabilities (bash, [CVE-2014-6277](https://access.redhat.com/security/cve/cve-2014-6277) and [CVE-2014-6278](https://access.redhat.com/security/cve/cve-2014-6278)); they are not even considered security issues by RedHat and thus will be unlikely to receive a patch in Amazon Linux, since it is based upon RedHat Enterprise Linux. 

From the [history](https://github.com/docker-library/official-images/pulls?q=is%3Apr+label%3Alibrary%2Famazonlinux) of image updates, it looks like the `amazonlinux` images are on a roughly 6-month release cycle.  If there is a specific vulnerability that would warrant publishing a new release, please point it out on the [Amazon Linux forums](https://forums.aws.amazon.com/forum.jspa?forumID=228)

Related issues in other Official Images:
https://github.com/docker-library/buildpack-deps/issues/46
https://github.com/docker-library/postgres/issues/286
https://github.com/docker-library/openjdk/issues/112
https://github.com/docker-library/drupal/issues/84
https://github.com/docker-library/official-images/issues/2740
https://github.com/docker-library/ruby/issues/117
https://github.com/docker-library/ruby/issues/94
https://github.com/docker-library/python/issues/152
https://github.com/docker-library/php/issues/242

**Comment by ilianaw** [comment]
Hi,

This appears to be the information available at https://hub.docker.com/r/library/amazonlinux/tags/latest/ (you may need to be logged in to view this).

This comes from Docker's security scanning infrastructure. AWS does not have any control or input into that at this time.

For information regarding vulnerabilities fixed in Amazon Linux, refer to https://alas.aws.amazon.com/. This, and the updateinfo.xml.gz that is part of the software repositories, is the only authoritative reference for security vulnerability information in Amazon Linux.

Please also note that `amazonlinux:latest` is currently *not* the Amazon Linux 2 LTS Candidate. This is explicitly `amazonlinux:2`. At a later date when AL2 graduates from its LTS Candidate status, `amazonlinux:latest` will become AL2.

If you have concerns about specific vulnerabilities, you can reach out here or to AWS Support.

Iliana
Amazon Linux
